FROM mswebench/darkreader_m_darkreader:base



COPY fix.patch /home/
COPY test.patch /home/
COPY check_git_changes.sh /home/
COPY prepare.sh /home/
COPY run.sh /home/
COPY test-run.sh /home/
COPY fix-run.sh /home/


RUN bash /home/prepare.sh



